name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform:
    name: Destroy Terraform Infra
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: environments/dev
        run: terraform init

      - name: Terraform Destroy
        working-directory: environments/dev
        run: terraform destroy -auto-approve
